import { NextRequest, NextResponse } from 'next/server';
import fs from 'node:fs';
import path from 'node:path';
import yaml from 'js-yaml';
import { extractUserFromRequest } from '../auth';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

type PackMeta = {
  name: string;
  title?: string | null;
  description?: string | null;
  ai?: { agentPrompt?: string | null } | null;
};

function loadCapabilities(projectRoot: string): any | null {
  try {
    const p = path.join(projectRoot, '.hit', 'generated', 'capabilities.json');
    if (!fs.existsSync(p)) return null;
    const raw = fs.readFileSync(p, 'utf8');
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

function loadHitConfig(projectRoot: string): any | null {
  try {
    // Generated by `hit run` from the app's hit.yaml.
    const p = path.join(projectRoot, 'public', 'hit-config.json');
    if (!fs.existsSync(p)) return null;
    const raw = fs.readFileSync(p, 'utf8');
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

function loadDashboardShellDefaults(projectRoot: string): Record<string, any> | null {
  // Try node_modules first (production), then monorepo workspace (dev).
  const candidates = [
    path.join(projectRoot, 'node_modules', '@hit', 'feature-pack-dashboard-shell', 'feature-pack.yaml'),
    path.join(projectRoot, '..', '..', 'hit-feature-packs', 'hit-feature-pack-dashboard-shell', 'feature-pack.yaml'),
  ];
  for (const p of candidates) {
    try {
      if (!fs.existsSync(p)) continue;
      const raw = fs.readFileSync(p, 'utf8');
      const obj = yaml.load(raw) as any;
      const schema = obj?.config?.schema;
      return schema && typeof schema === 'object' ? (schema as any) : null;
    } catch {
      // keep trying
    }
  }
  return null;
}

function isAdminUser(user: any): boolean {
  const roles = Array.isArray(user?.roles) ? user.roles : [];
  return roles.some((r: any) => String(r || '').toLowerCase() === 'admin' || String(r || '').toLowerCase() === 'superadmin');
}

export async function GET(request: NextRequest) {
  const user = extractUserFromRequest(request);
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const projectRoot = process.cwd();
  const caps = loadCapabilities(projectRoot);
  const packs: PackMeta[] = Array.isArray((caps as any)?.featurePacksDetailed) ? (caps as any).featurePacksDetailed : [];

  const hitConfig = loadHitConfig(projectRoot);
  const shellCfg = (hitConfig as any)?.featurePacks?.['dashboard-shell'];

  const shellDefaults = loadDashboardShellDefaults(projectRoot);
  const defaultNexusPrompt = shellDefaults?.nexus_prompt?.default;

  const nexusPrompt =
    (shellCfg && typeof (shellCfg as any).nexus_prompt === 'string' && String((shellCfg as any).nexus_prompt).trim()) ||
    (typeof defaultNexusPrompt === 'string' && defaultNexusPrompt.trim()) ||
    null;

  const debugFlag = (shellCfg as any)?.nexus_debug === true;
  const debugEnabled = Boolean(debugFlag && isAdminUser(user));

  return NextResponse.json({
    generated: Boolean((caps as any)?.generated),
    kind: 'hit-nexus-options',
    nexusPrompt,
    debugEnabled,
    packs,
  });
}

